export const headerText = 'تغییر رمز عبور'
export const currentPassText = 'رمز عبور فعلی'
export const newPassText = 'رمز عبور جدید'
export const repeatNewPassText = 'تکرار رمز عبور جدید'
export const confirmText = 'تایید'
export const missMatchPassTxt = 'رمز عبور جدید با تکرار آن مطابقت ندارد.'
export const wholeFieldValidationTxt = 'لطفا تمام فیلد ها را وارد نمایید.'