//checkUsernameScreen
export const enterPhoneNumber = 'شماره موبایل خود را وارد کنید'
export const confirm = 'تایید'
export const emptyUsername= 'لطفا شماره موبایل خود را وارد کنید'
//registerScreen
export const alias = 'نام مستعار'
export const password = 'رمز عبور'
export const passwordConfirmation1 = 'تکرار رمز عبور '
export const passwordConfirmation2 = 'جدید'
export const emptyAlias= 'لطفا نام مستعار را وارد کنید'
export const emptyPasswordConfirmation = 'لطفا تکرار رمز عبور را وارد کنید'
export const passwordIsNotMatch = 'رمز عبور با تکرار رمز مطابق نیست'
//verificationScreen
export const confirmVerificationButton = 'ثبت نام'
export const resendVerificationButton = 'کد را دریافت نکرده ام'
export const verificationCode = 'کد تایید'
export const emptyVerificationCode = 'لطفا کد تایید را وارد کنید'
export const enterVerificationCode1= 'کد امنیتی'
export const enterVerificationCode2= ' را وارد کنید'
export const sent = 'کد ارسال شد'
//loginScreen
export const emptyPassword= 'لطفا رمز عبور را وارد کنید'
export const forgotPassword = 'رمز عبور را فراموش کرده ام'
export const enterPassword = 'رمز عبور'
export const login = 'ورود'
export const newPassword3 = ' خود را وارد کنید'
export const newPassword2 = ' جدید'
export const newPassword1 = 'رمز عبور'
//splashScreen
export const retry = 'تلاش مجدد'
export const splashText = 'با مگزیلا، دسترسی به هزاران مجله'
//tab navigator
export const home = 'خانه' 
export const profile = 'پروفایل'
export const search = 'جستجو'
export const library = 'کتابخانه'
//toast
export const dangerToast = 'danger'
export const warningToast = 'warning'
export const successToast = 'success'
//splashScreen
export const app = 'مگزیلا'
//api errors
export const connectionError = 'خطا در اتصال به اینترنت'
export const requestError = 'خطا در برقراری ارتباط با سرویس دهنده'
export const noDataError = 'اشکال در اطلاعات دریافتی از سرویس دهنده'
export const error400 = 'اشکال در اطلاعات ارسالی'
export const error500 = 'سرویس دهنده با مشکل مواجه شد'
export const otherErrors = 'خطا در برقراری ارتباط'
//homeScrreen
export const category= 'دسته بندی ها'
// export const all = 'مشاهده همه'
//detailsScreen
export const view = 'تعداد بازدید: '
export const read = 'خواندن'
export const demo = 'نسخه دمو'
export const buyPlan = 'خرید اشتراک'
export const aboutMag  = 'درباره مجله' 
export const aboutIssue = 'درباره این شماره' 
export const magDescription = 'Magazine Description: '
//categoryScreen
export const searchboxHint = 'جستجو در بین دسته بندی ها ...'
export const emptyList = 'موردی یافت نشد.'
//profile
export const noPhoto = 'بدون عکس'
export const planStatus = 'وضعیت اشتراک: '
export const transactions = 'تراکنش ها'
export const addPlan = 'افزایش اشتراک'
export const changeProfileImage = 'تغییر عکس پروفایل'
export const name = 'نام'
export const lastName = 'نام خانوادگی'
export const education = 'تحصیلات'
export const birthdate = 'تاریخ تولد'
export const email = 'ایمیل'
export const saveInformation = 'ذخیره اطلاعات'
export const cancel = 'انصراف'
export const enterNewUsername1 = 'شماره تلفن '
export const enterNewUsername2 = 'جدید '
export const enterNewUsername3 = 'را وارد کنید'
export const changeUsername = 'تغییر شماره تلفن'
export const deleteAccount = 'حذف حساب کاربری'
export const deleteAccountConfirmation = 'آیا از حذف حساب کاربری خود اطمینان دارید؟'
export const changeInfo = 'تغییر اطلاعات کاربری'
export const continuee = 'ادامه'
export const accountSetting = 'تنظیمات حساب کاربری'
export const currentPassword = 'رمز عبور فعلی'
export const changePassword = 'تغییر رمز عبور'
